= AsciiDoc Publishing Toolbox
Andrea Esposito <esposito_andrea99@hotmail.com>
v0.0.0, 18 february 2020: Initial commit
:source-highlighter: rouge
:doctype: article
:toc: left

image:https://github.com/AsciiDoc-Publishing-Toolbox/asciidoc_publishing_toolbox/workflows/Ruby/badge.svg["Ruby"]
image:https://badge.fury.io/rb/asciidoc_publishing_toolbox.svg["Gem Version", link="https://badge.fury.io/rb/asciidoc_publishing_toolbox"]

== About the Project

ADPT (AsciiDoc Publishing Toolbox) is a simple publishing tool based on
AsciiDoc.

The goal is to create a tool with an interface that's similar to the one saw in
various package managers (like Node's `npm` or PHP's `composer`) specialized in
the creation, management and publishing of documents.

== How to install

The installation process it's simple. You just need to ensure that Ruby is
installed on your system. Once done, you can install it from RubyGems using the
following command.

[source,shell]
---------------
# Depending on your system, this may require admin privileges
gem install asciidoc_publishing_toolbox
---------------

== How to use

Once installed a new command, `adpt`, will be available. Use `adpt --help` to
get all the available options and commands. A typical use case would be the
following:

[source,shell]
--------------
# Initialize a new document in the directory document-folder
adpt init document-folder

# Add a new chapter to the document in the current directory
adpt chap -t "Chapter Title"

# Build the document in the current directory to HTML and PDF
adpt build
--------------

You can edit the document configuration using a text editor: it's a JSON file
that follows the https://asciidoc-publishing-toolbox.github.io/document-schema[ADPT's Document Schema].
